robot_model:
  description:
    ### upper body settings ########################################################
    bases:
      - idx: 0
        name: "PELVIS"
        shape: "CUBOID" # CUBOID, SPHERICAL
        size: {x: 0.5, y: 1.1, z: 1.5} # [m]
        link: "pelvis_link"
        link_to_feet_center_offset: {x: 0.00, y: 0.00, z: 0.00, roll:  0.00, pitch:  0.00, yaw:  0.00} # 3x[m] 3x[rad], transformation from body center to tf frame
        vis:
          mesh_offset: {x: 0.0, y: 0.00, z: 0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}
    
    ### foot settings ##############################################################
    base_foot: &base_foot
      - shape: "CUBOID" # CUBOID, SPHERICAL
        size: {x: 0.22, y: 0.15, z: 0.015} # [m]

    feet:
      - <<: *base_foot
        idx: 0
        name: "LEFT_FOOT"
        link: "l_leg_foot_link"
        # position (offset) of planner foot frame (center of sole) given in robot's "foot" link frame
        link_to_sole_offset: {x:  0.00, y:  0.0155, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00} # 3x[m] 3x[rad]
        # the neutral stance describes the pose of each foot (center of sole) relative to the (implicitly defined) robot center
        neutral_stance: {x:  0.00, y:  0.1085, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}
        vis:
          color: {r: 0.0, g: 1.0, b: 0.0, a: 0.6}
          mesh_resource: "package://thormang3_description/meshes/robotis_l_leg_foot.stl"
          # position of mesh frame given in foot sole frame
          mesh_offset: {x:  0.00, y: -0.0155, z:  0.0275, roll:  0.00, pitch:  0.00, yaw:  0.00}
          mesh_scale: [0.001, 0.001, 0.001]

      - <<: *base_foot
        idx: 1
        name: "RIGHT_FOOT"
        link: "r_leg_foot_link"
        # position (offset) of planner foot frame (center of sole) given in robot's "foot" link frame
        link_to_sole_offset: {x:  0.00, y: -0.0155, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00} # 3x[m] 3x[rad]
        # the neutral stance describes the pose of each foot (center of sole) relative to the (implicitly defined) robot center
        neutral_stance: {x:  0.00, y: -0.1085, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}
        vis:
          color: {r: 1.0, g: 0.0, b: 0.0, a: 0.6}
          mesh_resource: "package://thormang3_description/meshes/robotis_r_leg_foot.stl"
          # position of mesh frame given in foot sole frame
          mesh_offset: {x:  0.00, y:  0.0155, z:  0.0275, roll:  0.00, pitch:  0.00, yaw:  0.00}
          mesh_scale: [0.001, 0.001, 0.001]

    ### leg settings ###############################################################
    legs:
      - idx: 0
        name: "LEFT_LEG"
        root_link: "pelvis_link"
        tip_link: "l_leg_an_r_link"
        joints: ["l_leg_hip_y", "l_leg_hip_r", "l_leg_hip_p", "l_leg_kn_p", "l_leg_an_p", "l_leg_an_r"]

      - idx: 1
        name: "RIGHT_LEG"
        root_link: "pelvis_link"
        tip_link: "r_leg_an_r_link"
        joints: ["r_leg_hip_y", "r_leg_hip_r", "r_leg_hip_p", "r_leg_kn_p", "r_leg_an_p", "r_leg_an_r"]

    ### plugins ####################################################################
  plugins:
    kinematics:
      name: kdl_kinematics
      params:
        robot_description: "johnny5/robot_description"
        root_link: "base_link"
        center_to_root: {x: -0.03, y: 0.0, z: 0.722, roll: 0.0, pitch: 0.0, yaw: 0.0}
    gait_generator:
      name: bipedal_gait_generator

